spring.application.name=springboot-api-demo
server.port=8081

#PostgreSQL (ajusta usuario/clave/host segun tu entorno)
spring.datasource.url=jdbc:postgresql://localhost:5432/DB-U
spring.datasource.username=${DB_USER:Rafael}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true