spring.jpa.hibernate.ddl-auto=create 
#Usé create para asegurar un esquema limpio en cada ejecución mientras aprendo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect