spring.application.name=springboot-api-demo
server.port=8080

#PostgreSQL (ajusta usuario/clave/host según tu entorno)
spring.datasource.url=jdbc:postgresql://localhost:5432/PostgresSQL-U
spring.datasource.username=${DB_USER:Rafael}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

